/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogComment {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'createdAt' : Time,
  'blogPostId' : bigint,
  'email' : string,
  'approved' : boolean,
  'parentId' : [] | [bigint],
}
export interface BlogCommentInput {
  'content' : string,
  'name' : string,
  'blogPostId' : bigint,
  'email' : string,
  'parentId' : [] | [bigint],
}
export interface BlogInteractionSummary {
  'sharesCount' : bigint,
  'commentsCount' : bigint,
  'likesCount' : bigint,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'seoTitle' : string,
  'views' : bigint,
  'publishDate' : string,
  'published' : boolean,
  'author' : string,
  'likes' : bigint,
  'imageUrl' : string,
  'seoDescription' : string,
}
export interface CommercialVehicleFeatures {
  'bus' : boolean,
  'sixByTwo' : boolean,
  'speed' : boolean,
  'economical' : boolean,
  'fourByTwo' : boolean,
  'capacity' : boolean,
  'power' : boolean,
  'sixByFour' : boolean,
}
export interface Contact {
  'tenor' : [] | [bigint],
  'downPayment' : [] | [number],
  'date' : string,
  'name' : string,
  'unit' : string,
  'email' : string,
  'message' : string,
  'address' : string,
  'notes' : [] | [string],
  'phoneNumber' : string,
}
export interface CreditSimulation {
  'tenor' : [] | [bigint],
  'downPayment' : [] | [number],
  'date' : string,
  'name' : string,
  'unit' : string,
  'email' : string,
  'message' : string,
  'address' : string,
  'notes' : [] | [string],
  'phoneNumber' : string,
}
export interface Interaction {
  'itemId' : bigint,
  'sharesFacebook' : bigint,
  'shares' : bigint,
  'sharesTwitter' : bigint,
  'likes' : bigint,
  'sharesWhatsApp' : bigint,
}
export interface MediaAsset {
  'id' : bigint,
  'typ' : string,
  'url' : string,
  'size' : bigint,
  'folder' : string,
}
export interface Promotion {
  'id' : bigint,
  'terms' : string,
  'title' : string,
  'published' : boolean,
  'description' : string,
  'imageUrl' : string,
  'validUntil' : string,
}
export interface TechnicalSpecs {
  'weight' : string,
  'additionalFeatures' : Array<string>,
  'fuelCapacity' : string,
  'transmission' : string,
  'suspension' : string,
  'dimensions' : string,
  'engine' : string,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'review' : string,
  'city' : string,
  'published' : boolean,
  'imageUrl' : string,
  'rating' : number,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variant {
  'features' : Array<string>,
  'isPremium' : boolean,
  'name' : string,
  'priceAdjustment' : bigint,
}
export interface Vehicle {
  'id' : bigint,
  'commercialFeatures' : [] | [CommercialVehicleFeatures],
  'brochure' : string,
  'published' : boolean,
  'name' : string,
  'description' : string,
  'variants' : Array<Variant>,
  'specs' : TechnicalSpecs,
  'imageUrl' : string,
  'price' : bigint,
  'videoUrl' : [] | [string],
  'isCommercial' : boolean,
}
export interface VisitorStats {
  'activeUsers' : bigint,
  'todayTraffic' : bigint,
  'totalVisitors' : bigint,
  'pageViews' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogComment' : ActorMethod<[BlogCommentInput], BlogComment>,
  'addContact' : ActorMethod<[Contact], boolean>,
  'addCreditSimulation' : ActorMethod<[CreditSimulation], boolean>,
  'adminLogin' : ActorMethod<
    [string, string],
    [] | [{ 'token' : string, 'role' : string }]
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'approveBlogComment' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdminUser' : ActorMethod<
    [string, string, string, string],
    [] | [bigint]
  >,
  'createBlogPost' : ActorMethod<[string, BlogPost], boolean>,
  'createMediaAsset' : ActorMethod<[string, MediaAsset], boolean>,
  'createPromotion' : ActorMethod<[string, Promotion], boolean>,
  'createTestimonial' : ActorMethod<[string, Testimonial], boolean>,
  'createVehicle' : ActorMethod<[string, Vehicle], boolean>,
  'deleteBlogComment' : ActorMethod<[string, bigint], undefined>,
  'deleteBlogPost' : ActorMethod<[string, bigint], boolean>,
  'deleteContact' : ActorMethod<[string, bigint], boolean>,
  'deleteCreditSimulation' : ActorMethod<[string, bigint], boolean>,
  'deleteMediaAsset' : ActorMethod<[string, bigint], boolean>,
  'deletePromotion' : ActorMethod<[string, bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[string, bigint], boolean>,
  'deleteVehicle' : ActorMethod<[string, bigint], boolean>,
  'getAndIncrementBlogPostViews' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogComments' : ActorMethod<[bigint], Array<BlogComment>>,
  'getBlogInteractionSummary' : ActorMethod<[bigint], BlogInteractionSummary>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[string], [] | [Array<Contact>]>,
  'getCreditSimulations' : ActorMethod<
    [string],
    [] | [Array<CreditSimulation>]
  >,
  'getMediaAssets' : ActorMethod<[string], [] | [Array<MediaAsset>]>,
  'getProductInteraction' : ActorMethod<[bigint], [] | [Interaction]>,
  'getPromotion' : ActorMethod<[bigint], [] | [Promotion]>,
  'getPromotions' : ActorMethod<[], Array<Promotion>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], [] | [Vehicle]>,
  'getVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getVisitorStats' : ActorMethod<[string], [] | [VisitorStats]>,
  'incrementBlogLike' : ActorMethod<[bigint], bigint>,
  'incrementBlogShare' : ActorMethod<[bigint, string], bigint>,
  'incrementPageView' : ActorMethod<[], undefined>,
  'incrementVisitor' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shareProduct' : ActorMethod<[bigint, string], undefined>,
  'updateBlogComment' : ActorMethod<[string, bigint, string], undefined>,
  'updateBlogPost' : ActorMethod<[string, BlogPost], boolean>,
  'updatePromotion' : ActorMethod<[string, Promotion], boolean>,
  'updateTestimonial' : ActorMethod<[string, Testimonial], boolean>,
  'updateVehicle' : ActorMethod<[string, Vehicle], boolean>,
  'updateVisitorStats' : ActorMethod<[string, VisitorStats], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];