/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'tenor' : IDL.Opt(IDL.Nat),
  'downPayment' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const CreditSimulation = IDL.Record({
  'tenor' : IDL.Opt(IDL.Nat),
  'downPayment' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'seoTitle' : IDL.Text,
  'views' : IDL.Nat,
  'publishDate' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'seoDescription' : IDL.Text,
});
export const MediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'typ' : IDL.Text,
  'url' : IDL.Text,
  'size' : IDL.Nat,
  'folder' : IDL.Text,
});
export const Promotion = IDL.Record({
  'id' : IDL.Nat,
  'terms' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'validUntil' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'city' : IDL.Text,
  'published' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Float64,
});
export const CommercialVehicleFeatures = IDL.Record({
  'bus' : IDL.Bool,
  'sixByTwo' : IDL.Bool,
  'speed' : IDL.Bool,
  'economical' : IDL.Bool,
  'fourByTwo' : IDL.Bool,
  'capacity' : IDL.Bool,
  'power' : IDL.Bool,
  'sixByFour' : IDL.Bool,
});
export const Variant = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'priceAdjustment' : IDL.Nat,
});
export const TechnicalSpecs = IDL.Record({
  'weight' : IDL.Text,
  'additionalFeatures' : IDL.Vec(IDL.Text),
  'fuelCapacity' : IDL.Text,
  'transmission' : IDL.Text,
  'suspension' : IDL.Text,
  'dimensions' : IDL.Text,
  'engine' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'commercialFeatures' : IDL.Opt(CommercialVehicleFeatures),
  'brochure' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(Variant),
  'specs' : TechnicalSpecs,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
  'isCommercial' : IDL.Bool,
});
export const DebugHashCompareMethod = IDL.Variant({
  'textCompare' : IDL.Null,
  'hybridCompare' : IDL.Null,
  'bytesEqual' : IDL.Null,
  'failed' : IDL.Null,
});
export const AdminLoginDebugReport = IDL.Record({
  'sessionCreated' : IDL.Bool,
  'error' : IDL.Opt(IDL.Text),
  'hashCompareMethod' : DebugHashCompareMethod,
  'passwordMatch' : IDL.Bool,
  'userFound' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Interaction = IDL.Record({
  'itemId' : IDL.Nat,
  'sharesFacebook' : IDL.Nat,
  'shares' : IDL.Nat,
  'sharesTwitter' : IDL.Nat,
  'likes' : IDL.Nat,
  'sharesWhatsApp' : IDL.Nat,
});
export const VisitorStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'todayTraffic' : IDL.Nat,
  'totalVisitors' : IDL.Nat,
  'pageViews' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([Contact], [], []),
  'addCreditSimulation' : IDL.Func([CreditSimulation], [], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdminUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'createBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
  'createMediaAsset' : IDL.Func([IDL.Text, MediaAsset], [], []),
  'createPromotion' : IDL.Func([IDL.Text, Promotion], [], []),
  'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'createVehicle' : IDL.Func([IDL.Text, Vehicle], [], []),
  'debugAdminLogin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [AdminLoginDebugReport],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteCreditSimulation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteMediaAsset' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePromotion' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Contact))], ['query']),
  'getCreditSimulations' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(CreditSimulation))],
      ['query'],
    ),
  'getMediaAssets' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(MediaAsset))],
      ['query'],
    ),
  'getProductInteraction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Interaction)],
      ['query'],
    ),
  'getPromotion' : IDL.Func([IDL.Nat], [IDL.Opt(Promotion)], ['query']),
  'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'getVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getVisitorStats' : IDL.Func([IDL.Text], [IDL.Opt(VisitorStats)], ['query']),
  'incrementPageView' : IDL.Func([], [], []),
  'incrementVisitor' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareProduct' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'toggleDebugMode' : IDL.Func([IDL.Bool], [], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
  'updatePromotion' : IDL.Func([IDL.Text, Promotion], [], []),
  'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'updateVehicle' : IDL.Func([IDL.Text, Vehicle], [], []),
  'updateVisitorStats' : IDL.Func([IDL.Text, VisitorStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'tenor' : IDL.Opt(IDL.Nat),
    'downPayment' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const CreditSimulation = IDL.Record({
    'tenor' : IDL.Opt(IDL.Nat),
    'downPayment' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'seoTitle' : IDL.Text,
    'views' : IDL.Nat,
    'publishDate' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'seoDescription' : IDL.Text,
  });
  const MediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'typ' : IDL.Text,
    'url' : IDL.Text,
    'size' : IDL.Nat,
    'folder' : IDL.Text,
  });
  const Promotion = IDL.Record({
    'id' : IDL.Nat,
    'terms' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'validUntil' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'city' : IDL.Text,
    'published' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const CommercialVehicleFeatures = IDL.Record({
    'bus' : IDL.Bool,
    'sixByTwo' : IDL.Bool,
    'speed' : IDL.Bool,
    'economical' : IDL.Bool,
    'fourByTwo' : IDL.Bool,
    'capacity' : IDL.Bool,
    'power' : IDL.Bool,
    'sixByFour' : IDL.Bool,
  });
  const Variant = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'priceAdjustment' : IDL.Nat,
  });
  const TechnicalSpecs = IDL.Record({
    'weight' : IDL.Text,
    'additionalFeatures' : IDL.Vec(IDL.Text),
    'fuelCapacity' : IDL.Text,
    'transmission' : IDL.Text,
    'suspension' : IDL.Text,
    'dimensions' : IDL.Text,
    'engine' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'commercialFeatures' : IDL.Opt(CommercialVehicleFeatures),
    'brochure' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(Variant),
    'specs' : TechnicalSpecs,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
    'isCommercial' : IDL.Bool,
  });
  const DebugHashCompareMethod = IDL.Variant({
    'textCompare' : IDL.Null,
    'hybridCompare' : IDL.Null,
    'bytesEqual' : IDL.Null,
    'failed' : IDL.Null,
  });
  const AdminLoginDebugReport = IDL.Record({
    'sessionCreated' : IDL.Bool,
    'error' : IDL.Opt(IDL.Text),
    'hashCompareMethod' : DebugHashCompareMethod,
    'passwordMatch' : IDL.Bool,
    'userFound' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Interaction = IDL.Record({
    'itemId' : IDL.Nat,
    'sharesFacebook' : IDL.Nat,
    'shares' : IDL.Nat,
    'sharesTwitter' : IDL.Nat,
    'likes' : IDL.Nat,
    'sharesWhatsApp' : IDL.Nat,
  });
  const VisitorStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'todayTraffic' : IDL.Nat,
    'totalVisitors' : IDL.Nat,
    'pageViews' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([Contact], [], []),
    'addCreditSimulation' : IDL.Func([CreditSimulation], [], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdminUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'createBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
    'createMediaAsset' : IDL.Func([IDL.Text, MediaAsset], [], []),
    'createPromotion' : IDL.Func([IDL.Text, Promotion], [], []),
    'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'createVehicle' : IDL.Func([IDL.Text, Vehicle], [], []),
    'debugAdminLogin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [AdminLoginDebugReport],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteCreditSimulation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteMediaAsset' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePromotion' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Contact))],
        ['query'],
      ),
    'getCreditSimulations' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(CreditSimulation))],
        ['query'],
      ),
    'getMediaAssets' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(MediaAsset))],
        ['query'],
      ),
    'getProductInteraction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Interaction)],
        ['query'],
      ),
    'getPromotion' : IDL.Func([IDL.Nat], [IDL.Opt(Promotion)], ['query']),
    'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'getVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getVisitorStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VisitorStats)],
        ['query'],
      ),
    'incrementPageView' : IDL.Func([], [], []),
    'incrementVisitor' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareProduct' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'toggleDebugMode' : IDL.Func([IDL.Bool], [], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
    'updatePromotion' : IDL.Func([IDL.Text, Promotion], [], []),
    'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'updateVehicle' : IDL.Func([IDL.Text, Vehicle], [], []),
    'updateVisitorStats' : IDL.Func([IDL.Text, VisitorStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };