/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlogCommentInput = IDL.Record({
  'content' : IDL.Text,
  'name' : IDL.Text,
  'blogPostId' : IDL.Nat,
  'email' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const BlogComment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'blogPostId' : IDL.Nat,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'tenor' : IDL.Opt(IDL.Nat),
  'downPayment' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const CreditSimulation = IDL.Record({
  'tenor' : IDL.Opt(IDL.Nat),
  'downPayment' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'seoTitle' : IDL.Text,
  'views' : IDL.Nat,
  'publishDate' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'seoDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'typ' : IDL.Text,
  'url' : IDL.Text,
  'externalBlob' : IDL.Opt(ExternalBlob),
  'size' : IDL.Nat,
  'legacyDataUrl' : IDL.Opt(IDL.Text),
  'folder' : IDL.Text,
});
export const Promotion = IDL.Record({
  'id' : IDL.Nat,
  'terms' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'validUntil' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'city' : IDL.Text,
  'published' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Float64,
});
export const CommercialVehicleFeatures = IDL.Record({
  'bus' : IDL.Bool,
  'sixByTwo' : IDL.Bool,
  'speed' : IDL.Bool,
  'economical' : IDL.Bool,
  'fourByTwo' : IDL.Bool,
  'capacity' : IDL.Bool,
  'power' : IDL.Bool,
  'sixByFour' : IDL.Bool,
});
export const Variant = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'priceAdjustment' : IDL.Nat,
});
export const TechnicalSpecs = IDL.Record({
  'weight' : IDL.Text,
  'additionalFeatures' : IDL.Vec(IDL.Text),
  'fuelCapacity' : IDL.Text,
  'transmission' : IDL.Text,
  'suspension' : IDL.Text,
  'dimensions' : IDL.Text,
  'engine' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'commercialFeatures' : IDL.Opt(CommercialVehicleFeatures),
  'brochure' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(Variant),
  'specs' : TechnicalSpecs,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
  'isCommercial' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SiteBanner = IDL.Record({
  'id' : IDL.Text,
  'updatedAt' : Time,
  'updatedBy' : IDL.Nat,
  'imageUrl' : IDL.Text,
});
export const BlogPostId = IDL.Nat;
export const BlogInteractionSummary = IDL.Record({
  'sharesCount' : IDL.Nat,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
});
export const ExtendedVisitorStats = IDL.Record({
  'todayTraffic' : IDL.Nat,
  'monthlyTraffic' : IDL.Nat,
  'totalVisitors' : IDL.Nat,
  'yesterdayTraffic' : IDL.Nat,
  'yearlyTraffic' : IDL.Nat,
  'onlineVisitors' : IDL.Nat,
  'pageViews' : IDL.Nat,
  'weeklyTraffic' : IDL.Nat,
});
export const SimpleMediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'typ' : IDL.Text,
  'url' : IDL.Text,
  'size' : IDL.Nat,
  'folder' : IDL.Text,
});
export const Interaction = IDL.Record({
  'itemId' : IDL.Nat,
  'sharesFacebook' : IDL.Nat,
  'shares' : IDL.Nat,
  'sharesTwitter' : IDL.Nat,
  'likes' : IDL.Nat,
  'sharesWhatsApp' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogComment' : IDL.Func([BlogCommentInput], [BlogComment], []),
  'addContact' : IDL.Func([Contact], [], []),
  'addCreditSimulation' : IDL.Func([CreditSimulation], [], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdminUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'createBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Bool], []),
  'createMediaAsset' : IDL.Func([IDL.Text, MediaAsset], [IDL.Bool], []),
  'createPromotion' : IDL.Func([IDL.Text, Promotion], [IDL.Bool], []),
  'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [IDL.Bool], []),
  'createVehicle' : IDL.Func([IDL.Text, Vehicle], [IDL.Bool], []),
  'deleteBlogComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteCreditSimulation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteMediaAsset' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deletePromotion' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteVehicle' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAdminUserProfile' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(UserProfile)],
      [],
    ),
  'getAdminUserProfileByIdToken' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(UserProfile)],
      [],
    ),
  'getAllSiteBanners' : IDL.Func([IDL.Text], [IDL.Vec(SiteBanner)], []),
  'getAndIncrementBlogPostViews' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], []),
  'getBlogComment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Opt(BlogComment)],
      [],
    ),
  'getBlogComments' : IDL.Func([BlogPostId], [IDL.Vec(BlogComment)], ['query']),
  'getBlogInteractionSummary' : IDL.Func(
      [IDL.Nat],
      [BlogInteractionSummary],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Contact))], []),
  'getCreditSimulations' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(CreditSimulation))],
      [],
    ),
  'getExtendedVisitorStats' : IDL.Func([IDL.Text], [ExtendedVisitorStats], []),
  'getFooterVisitorStats' : IDL.Func([], [ExtendedVisitorStats], []),
  'getMainBannerImageUrls' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getMediaAssets' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(SimpleMediaAsset)],
      [],
    ),
  'getProductInteraction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Interaction)],
      ['query'],
    ),
  'getPromotion' : IDL.Func([IDL.Nat], [IDL.Opt(Promotion)], ['query']),
  'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getSiteBanner' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SiteBanner)], []),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'getVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'incrementBlogLike' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'incrementBlogShare' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'incrementPageView' : IDL.Func([], [], []),
  'incrementVisitor' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveAdminUserProfile' : IDL.Func([IDL.Text, IDL.Nat, UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareProduct' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateBlogComment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Bool], []),
  'updateMainBannerImageUrls' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'updatePromotion' : IDL.Func([IDL.Text, Promotion], [IDL.Bool], []),
  'updateSiteBanner' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [IDL.Bool], []),
  'updateVehicle' : IDL.Func([IDL.Text, Vehicle], [IDL.Bool], []),
  'userActivity' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlogCommentInput = IDL.Record({
    'content' : IDL.Text,
    'name' : IDL.Text,
    'blogPostId' : IDL.Nat,
    'email' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const BlogComment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'blogPostId' : IDL.Nat,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'tenor' : IDL.Opt(IDL.Nat),
    'downPayment' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const CreditSimulation = IDL.Record({
    'tenor' : IDL.Opt(IDL.Nat),
    'downPayment' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'seoTitle' : IDL.Text,
    'views' : IDL.Nat,
    'publishDate' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'seoDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'typ' : IDL.Text,
    'url' : IDL.Text,
    'externalBlob' : IDL.Opt(ExternalBlob),
    'size' : IDL.Nat,
    'legacyDataUrl' : IDL.Opt(IDL.Text),
    'folder' : IDL.Text,
  });
  const Promotion = IDL.Record({
    'id' : IDL.Nat,
    'terms' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'validUntil' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'city' : IDL.Text,
    'published' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const CommercialVehicleFeatures = IDL.Record({
    'bus' : IDL.Bool,
    'sixByTwo' : IDL.Bool,
    'speed' : IDL.Bool,
    'economical' : IDL.Bool,
    'fourByTwo' : IDL.Bool,
    'capacity' : IDL.Bool,
    'power' : IDL.Bool,
    'sixByFour' : IDL.Bool,
  });
  const Variant = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'priceAdjustment' : IDL.Nat,
  });
  const TechnicalSpecs = IDL.Record({
    'weight' : IDL.Text,
    'additionalFeatures' : IDL.Vec(IDL.Text),
    'fuelCapacity' : IDL.Text,
    'transmission' : IDL.Text,
    'suspension' : IDL.Text,
    'dimensions' : IDL.Text,
    'engine' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'commercialFeatures' : IDL.Opt(CommercialVehicleFeatures),
    'brochure' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(Variant),
    'specs' : TechnicalSpecs,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
    'isCommercial' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SiteBanner = IDL.Record({
    'id' : IDL.Text,
    'updatedAt' : Time,
    'updatedBy' : IDL.Nat,
    'imageUrl' : IDL.Text,
  });
  const BlogPostId = IDL.Nat;
  const BlogInteractionSummary = IDL.Record({
    'sharesCount' : IDL.Nat,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
  });
  const ExtendedVisitorStats = IDL.Record({
    'todayTraffic' : IDL.Nat,
    'monthlyTraffic' : IDL.Nat,
    'totalVisitors' : IDL.Nat,
    'yesterdayTraffic' : IDL.Nat,
    'yearlyTraffic' : IDL.Nat,
    'onlineVisitors' : IDL.Nat,
    'pageViews' : IDL.Nat,
    'weeklyTraffic' : IDL.Nat,
  });
  const SimpleMediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'typ' : IDL.Text,
    'url' : IDL.Text,
    'size' : IDL.Nat,
    'folder' : IDL.Text,
  });
  const Interaction = IDL.Record({
    'itemId' : IDL.Nat,
    'sharesFacebook' : IDL.Nat,
    'shares' : IDL.Nat,
    'sharesTwitter' : IDL.Nat,
    'likes' : IDL.Nat,
    'sharesWhatsApp' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogComment' : IDL.Func([BlogCommentInput], [BlogComment], []),
    'addContact' : IDL.Func([Contact], [], []),
    'addCreditSimulation' : IDL.Func([CreditSimulation], [], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdminUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'createBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Bool], []),
    'createMediaAsset' : IDL.Func([IDL.Text, MediaAsset], [IDL.Bool], []),
    'createPromotion' : IDL.Func([IDL.Text, Promotion], [IDL.Bool], []),
    'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [IDL.Bool], []),
    'createVehicle' : IDL.Func([IDL.Text, Vehicle], [IDL.Bool], []),
    'deleteBlogComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteCreditSimulation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteMediaAsset' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deletePromotion' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteVehicle' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAdminUserProfile' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'getAdminUserProfileByIdToken' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'getAllSiteBanners' : IDL.Func([IDL.Text], [IDL.Vec(SiteBanner)], []),
    'getAndIncrementBlogPostViews' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'getBlogComment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Opt(BlogComment)],
        [],
      ),
    'getBlogComments' : IDL.Func(
        [BlogPostId],
        [IDL.Vec(BlogComment)],
        ['query'],
      ),
    'getBlogInteractionSummary' : IDL.Func(
        [IDL.Nat],
        [BlogInteractionSummary],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Contact))], []),
    'getCreditSimulations' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(CreditSimulation))],
        [],
      ),
    'getExtendedVisitorStats' : IDL.Func(
        [IDL.Text],
        [ExtendedVisitorStats],
        [],
      ),
    'getFooterVisitorStats' : IDL.Func([], [ExtendedVisitorStats], []),
    'getMainBannerImageUrls' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getMediaAssets' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(SimpleMediaAsset)],
        [],
      ),
    'getProductInteraction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Interaction)],
        ['query'],
      ),
    'getPromotion' : IDL.Func([IDL.Nat], [IDL.Opt(Promotion)], ['query']),
    'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getSiteBanner' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SiteBanner)], []),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'getVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'incrementBlogLike' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'incrementBlogShare' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'incrementPageView' : IDL.Func([], [], []),
    'incrementVisitor' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveAdminUserProfile' : IDL.Func([IDL.Text, IDL.Nat, UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareProduct' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateBlogComment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Bool], []),
    'updateMainBannerImageUrls' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updatePromotion' : IDL.Func([IDL.Text, Promotion], [IDL.Bool], []),
    'updateSiteBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [IDL.Bool], []),
    'updateVehicle' : IDL.Func([IDL.Text, Vehicle], [IDL.Bool], []),
    'userActivity' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };