/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Promotion {
    id: bigint;
    terms: string;
    title: string;
    published: boolean;
    description: string;
    imageUrl: string;
    validUntil: string;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    seoTitle: string;
    views: bigint;
    publishDate: string;
    published: boolean;
    author: string;
    likes: bigint;
    imageUrl: string;
    seoDescription: string;
}
export type Time = bigint;
export interface BlogCommentInput {
    content: string;
    name: string;
    blogPostId: bigint;
    email: string;
    parentId?: bigint;
}
export interface MediaAsset {
    id: bigint;
    typ: string;
    url: string;
    size: bigint;
    folder: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CreditSimulation {
    tenor?: bigint;
    downPayment?: number;
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes?: string;
    phoneNumber: string;
}
export interface Variant {
    features: Array<string>;
    isPremium: boolean;
    name: string;
    priceAdjustment: bigint;
}
export interface Contact {
    tenor?: bigint;
    downPayment?: number;
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes?: string;
    phoneNumber: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VisitorStats {
    activeUsers: bigint;
    todayTraffic: bigint;
    totalVisitors: bigint;
    pageViews: bigint;
}
export interface Vehicle {
    id: bigint;
    commercialFeatures?: CommercialVehicleFeatures;
    brochure: string;
    published: boolean;
    name: string;
    description: string;
    variants: Array<Variant>;
    specs: TechnicalSpecs;
    imageUrl: string;
    price: bigint;
    videoUrl?: string;
    isCommercial: boolean;
}
export interface CommercialVehicleFeatures {
    bus: boolean;
    sixByTwo: boolean;
    speed: boolean;
    economical: boolean;
    fourByTwo: boolean;
    capacity: boolean;
    power: boolean;
    sixByFour: boolean;
}
export interface BlogComment {
    id: bigint;
    content: string;
    name: string;
    createdAt: Time;
    blogPostId: bigint;
    email: string;
    approved: boolean;
    parentId?: bigint;
}
export interface TechnicalSpecs {
    weight: string;
    additionalFeatures: Array<string>;
    fuelCapacity: string;
    transmission: string;
    suspension: string;
    dimensions: string;
    engine: string;
}
export interface BlogInteractionSummary {
    sharesCount: bigint;
    commentsCount: bigint;
    likesCount: bigint;
}
export interface Interaction {
    itemId: bigint;
    sharesFacebook: bigint;
    shares: bigint;
    sharesTwitter: bigint;
    likes: bigint;
    sharesWhatsApp: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Testimonial {
    id: bigint;
    customerName: string;
    review: string;
    city: string;
    published: boolean;
    imageUrl: string;
    rating: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBlogComment(blogCommentInput: BlogCommentInput): Promise<BlogComment>;
    addContact(contact: Contact): Promise<boolean>;
    addCreditSimulation(simulation: CreditSimulation): Promise<boolean>;
    adminLogin(email: string, password: string): Promise<{
        token: string;
        role: string;
    } | null>;
    adminLogout(token: string): Promise<void>;
    approveBlogComment(sessionToken: string, commentId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdminUser(sessionToken: string, email: string, password: string, role: string): Promise<bigint | null>;
    createBlogPost(sessionToken: string, post: BlogPost): Promise<boolean>;
    createMediaAsset(sessionToken: string, asset: MediaAsset): Promise<boolean>;
    createPromotion(sessionToken: string, promotion: Promotion): Promise<boolean>;
    createTestimonial(sessionToken: string, testimonial: Testimonial): Promise<boolean>;
    createVehicle(sessionToken: string, vehicle: Vehicle): Promise<boolean>;
    deleteBlogComment(sessionToken: string, commentId: bigint): Promise<void>;
    deleteBlogPost(sessionToken: string, id: bigint): Promise<boolean>;
    deleteContact(sessionToken: string, id: bigint): Promise<boolean>;
    deleteCreditSimulation(sessionToken: string, id: bigint): Promise<boolean>;
    deleteMediaAsset(sessionToken: string, id: bigint): Promise<boolean>;
    deletePromotion(sessionToken: string, id: bigint): Promise<boolean>;
    deleteTestimonial(sessionToken: string, id: bigint): Promise<boolean>;
    deleteVehicle(sessionToken: string, id: bigint): Promise<boolean>;
    getAndIncrementBlogPostViews(blogPostId: bigint): Promise<BlogPost | null>;
    getBlogComments(blogPostId: bigint): Promise<Array<BlogComment>>;
    getBlogInteractionSummary(blogPostId: bigint): Promise<BlogInteractionSummary>;
    getBlogPost(id: bigint): Promise<BlogPost | null>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContacts(sessionToken: string): Promise<Array<Contact> | null>;
    getCreditSimulations(sessionToken: string): Promise<Array<CreditSimulation> | null>;
    getMediaAssets(sessionToken: string): Promise<Array<MediaAsset> | null>;
    getProductInteraction(itemId: bigint): Promise<Interaction | null>;
    getPromotion(id: bigint): Promise<Promotion | null>;
    getPromotions(): Promise<Array<Promotion>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVehicle(id: bigint): Promise<Vehicle | null>;
    getVehicles(): Promise<Array<Vehicle>>;
    getVisitorStats(sessionToken: string): Promise<VisitorStats | null>;
    incrementBlogLike(blogPostId: bigint): Promise<bigint>;
    incrementBlogShare(blogPostId: bigint, _platform: string): Promise<bigint>;
    incrementPageView(): Promise<void>;
    incrementVisitor(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    likeProduct(itemId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    shareProduct(itemId: bigint, platform: string): Promise<void>;
    updateBlogComment(sessionToken: string, commentId: bigint, content: string): Promise<void>;
    updateBlogPost(sessionToken: string, post: BlogPost): Promise<boolean>;
    updatePromotion(sessionToken: string, promotion: Promotion): Promise<boolean>;
    updateTestimonial(sessionToken: string, testimonial: Testimonial): Promise<boolean>;
    updateVehicle(sessionToken: string, vehicle: Vehicle): Promise<boolean>;
    updateVisitorStats(sessionToken: string, stats: VisitorStats): Promise<boolean>;
}
import type { BlogComment as _BlogComment, BlogCommentInput as _BlogCommentInput, BlogPost as _BlogPost, CommercialVehicleFeatures as _CommercialVehicleFeatures, Contact as _Contact, CreditSimulation as _CreditSimulation, Interaction as _Interaction, MediaAsset as _MediaAsset, Promotion as _Promotion, TechnicalSpecs as _TechnicalSpecs, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Variant as _Variant, Vehicle as _Vehicle, VisitorStats as _VisitorStats, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBlogComment(arg0: BlogCommentInput): Promise<BlogComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogComment(to_candid_BlogCommentInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogComment_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogComment(to_candid_BlogCommentInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogComment_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addContact(arg0: Contact): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(to_candid_Contact_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(to_candid_Contact_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCreditSimulation(arg0: CreditSimulation): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCreditSimulation(to_candid_CreditSimulation_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCreditSimulation(to_candid_CreditSimulation_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        token: string;
        role: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async approveBlogComment(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBlogComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBlogComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdminUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminUser(arg0, arg1, arg2, arg3);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminUser(arg0, arg1, arg2, arg3);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: string, arg1: BlogPost): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1);
            return result;
        }
    }
    async createMediaAsset(arg0: string, arg1: MediaAsset): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createMediaAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMediaAsset(arg0, arg1);
            return result;
        }
    }
    async createPromotion(arg0: string, arg1: Promotion): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createPromotion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPromotion(arg0, arg1);
            return result;
        }
    }
    async createTestimonial(arg0: string, arg1: Testimonial): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0, arg1);
            return result;
        }
    }
    async createVehicle(arg0: string, arg1: Vehicle): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createVehicle(arg0, to_candid_Vehicle_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVehicle(arg0, to_candid_Vehicle_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBlogComment(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogComment(arg0, arg1);
            return result;
        }
    }
    async deleteBlogPost(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0, arg1);
            return result;
        }
    }
    async deleteContact(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0, arg1);
            return result;
        }
    }
    async deleteCreditSimulation(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCreditSimulation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCreditSimulation(arg0, arg1);
            return result;
        }
    }
    async deleteMediaAsset(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaAsset(arg0, arg1);
            return result;
        }
    }
    async deletePromotion(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePromotion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePromotion(arg0, arg1);
            return result;
        }
    }
    async deleteTestimonial(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0, arg1);
            return result;
        }
    }
    async deleteVehicle(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0, arg1);
            return result;
        }
    }
    async getAndIncrementBlogPostViews(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAndIncrementBlogPostViews(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAndIncrementBlogPostViews(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogComments(arg0: bigint): Promise<Array<BlogComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogComments(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogComments(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogInteractionSummary(arg0: bigint): Promise<BlogInteractionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogInteractionSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogInteractionSummary(arg0);
            return result;
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(arg0: string): Promise<Array<Contact> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditSimulations(arg0: string): Promise<Array<CreditSimulation> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditSimulations(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditSimulations(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaAssets(arg0: string): Promise<Array<MediaAsset> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaAssets(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaAssets(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductInteraction(arg0: bigint): Promise<Interaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductInteraction(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductInteraction(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromotion(arg0: bigint): Promise<Promotion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromotion(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromotion(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromotions(): Promise<Array<Promotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromotions();
            return result;
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: bigint): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicles();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicles();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorStats(arg0: string): Promise<VisitorStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorStats(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorStats(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementBlogLike(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementBlogLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementBlogLike(arg0);
            return result;
        }
    }
    async incrementBlogShare(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementBlogShare(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementBlogShare(arg0, arg1);
            return result;
        }
    }
    async incrementPageView(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementPageView();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementPageView();
            return result;
        }
    }
    async incrementVisitor(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementVisitor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementVisitor();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeProduct(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async shareProduct(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareProduct(arg0, arg1);
            return result;
        }
    }
    async updateBlogComment(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogComment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPost): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1);
            return result;
        }
    }
    async updatePromotion(arg0: string, arg1: Promotion): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromotion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromotion(arg0, arg1);
            return result;
        }
    }
    async updateTestimonial(arg0: string, arg1: Testimonial): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1);
            return result;
        }
    }
    async updateVehicle(arg0: string, arg1: Vehicle): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0, to_candid_Vehicle_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0, to_candid_Vehicle_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVisitorStats(arg0: string, arg1: VisitorStats): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitorStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitorStats(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BlogComment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogComment): BlogComment {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Contact_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CreditSimulation_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditSimulation): CreditSimulation {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        token: string;
        role: string;
    }]): {
    token: string;
    role: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Contact>]): Array<Contact> | null {
    return value.length === 0 ? null : from_candid_vec_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_CreditSimulation>]): Array<CreditSimulation> | null {
    return value.length === 0 ? null : from_candid_vec_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_MediaAsset>]): Array<MediaAsset> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Interaction]): Interaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Promotion]): Promotion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : from_candid_Vehicle_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommercialVehicleFeatures]): CommercialVehicleFeatures | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VisitorStats]): VisitorStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    name: string;
    createdAt: _Time;
    blogPostId: bigint;
    email: string;
    approved: boolean;
    parentId: [] | [bigint];
}): {
    id: bigint;
    content: string;
    name: string;
    createdAt: Time;
    blogPostId: bigint;
    email: string;
    approved: boolean;
    parentId?: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        name: value.name,
        createdAt: value.createdAt,
        blogPostId: value.blogPostId,
        email: value.email,
        approved: value.approved,
        parentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tenor: [] | [bigint];
    downPayment: [] | [number];
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes: [] | [string];
    phoneNumber: string;
}): {
    tenor?: bigint;
    downPayment?: number;
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes?: string;
    phoneNumber: string;
} {
    return {
        tenor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tenor)),
        downPayment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.downPayment)),
        date: value.date,
        name: value.name,
        unit: value.unit,
        email: value.email,
        message: value.message,
        address: value.address,
        notes: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.notes)),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    commercialFeatures: [] | [_CommercialVehicleFeatures];
    brochure: string;
    published: boolean;
    name: string;
    description: string;
    variants: Array<_Variant>;
    specs: _TechnicalSpecs;
    imageUrl: string;
    price: bigint;
    videoUrl: [] | [string];
    isCommercial: boolean;
}): {
    id: bigint;
    commercialFeatures?: CommercialVehicleFeatures;
    brochure: string;
    published: boolean;
    name: string;
    description: string;
    variants: Array<Variant>;
    specs: TechnicalSpecs;
    imageUrl: string;
    price: bigint;
    videoUrl?: string;
    isCommercial: boolean;
} {
    return {
        id: value.id,
        commercialFeatures: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.commercialFeatures)),
        brochure: value.brochure,
        published: value.published,
        name: value.name,
        description: value.description,
        variants: value.variants,
        specs: value.specs,
        imageUrl: value.imageUrl,
        price: value.price,
        videoUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.videoUrl)),
        isCommercial: value.isCommercial
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogComment>): Array<BlogComment> {
    return value.map((x)=>from_candid_BlogComment_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contact>): Array<Contact> {
    return value.map((x)=>from_candid_Contact_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreditSimulation>): Array<CreditSimulation> {
    return value.map((x)=>from_candid_CreditSimulation_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n38(_uploadFile, _downloadFile, x));
}
function to_candid_BlogCommentInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCommentInput): _BlogCommentInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Contact_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contact): _Contact {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CreditSimulation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreditSimulation): _CreditSimulation {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Vehicle_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vehicle): _Vehicle {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tenor?: bigint;
    downPayment?: number;
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes?: string;
    phoneNumber: string;
}): {
    tenor: [] | [bigint];
    downPayment: [] | [number];
    date: string;
    name: string;
    unit: string;
    email: string;
    message: string;
    address: string;
    notes: [] | [string];
    phoneNumber: string;
} {
    return {
        tenor: value.tenor ? candid_some(value.tenor) : candid_none(),
        downPayment: value.downPayment ? candid_some(value.downPayment) : candid_none(),
        date: value.date,
        name: value.name,
        unit: value.unit,
        email: value.email,
        message: value.message,
        address: value.address,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    commercialFeatures?: CommercialVehicleFeatures;
    brochure: string;
    published: boolean;
    name: string;
    description: string;
    variants: Array<Variant>;
    specs: TechnicalSpecs;
    imageUrl: string;
    price: bigint;
    videoUrl?: string;
    isCommercial: boolean;
}): {
    id: bigint;
    commercialFeatures: [] | [_CommercialVehicleFeatures];
    brochure: string;
    published: boolean;
    name: string;
    description: string;
    variants: Array<_Variant>;
    specs: _TechnicalSpecs;
    imageUrl: string;
    price: bigint;
    videoUrl: [] | [string];
    isCommercial: boolean;
} {
    return {
        id: value.id,
        commercialFeatures: value.commercialFeatures ? candid_some(value.commercialFeatures) : candid_none(),
        brochure: value.brochure,
        published: value.published,
        name: value.name,
        description: value.description,
        variants: value.variants,
        specs: value.specs,
        imageUrl: value.imageUrl,
        price: value.price,
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none(),
        isCommercial: value.isCommercial
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    name: string;
    blogPostId: bigint;
    email: string;
    parentId?: bigint;
}): {
    content: string;
    name: string;
    blogPostId: bigint;
    email: string;
    parentId: [] | [bigint];
} {
    return {
        content: value.content,
        name: value.name,
        blogPostId: value.blogPostId,
        email: value.email,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
